contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #multiplesequencealign channel"
    url: https://nfcore.slack.com/channels/multiplesequencealign
    about: Discussion about the nf-core/multiplesequencealign pipeline
