contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #msa channel"
    url: https://nfcore.slack.com/channels/msa
    about: Discussion about the nf-core/msa pipeline
